

# define the C compiler to use
CC = g++

# define any compile-time flags
CFLAGS = -Wall -g

all: scheduler client hospitalA hospitalB hospitalC

scheduler: scheduler.cpp
	$(CC) $(CFLAGS) -o scheduler scheduler.cpp

client: client.cpp
	$(CC) $(CFLAGS) -o client client.cpp

hospitalA: hospitalA.cpp
	$(CC) $(CFLAGS) -o hospitalA hospitalA.cpp

hospitalB: hospitalB.cpp
	$(CC) $(CFLAGS) -o hospitalB hospitalB.cpp

hospitalC:hospitalC.cpp
	$(CC) $(CFLAGS) -o hospitalC hospitalC.cpp


	


